name: 'Pull Request'
on:
  pull_request:
    branches:
      - master
env:
  IMAGE_NAME: dwpdigital/cognito-guacamole-extension

jobs:
  pull_request:

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build-docker-image
        run: make docker

# ================================================
      - name: upload-jar-and-guac-artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/libs/*.jar
            build/resources/main/*.json
# ================================================

      - name: snyk-scan
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}
          args: --file=./docker/Dockerfile --policy-path=./.snyk --severity-threshold=high --exclude-base-image-vulns --org=dwp-dataworks

# ================================================
  publish-docker:
    runs-on: ubuntu-latest
    needs: pull_request
    steps:
      - uses: actions/checkout@v2

      - name: download-artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: move-files-for-publish
        run: |
          cp ${GITHUB_WORKSPACE}/libs/*.jar ./docker
          cp ${GITHUB_WORKSPACE}/resources/main/*.json ./docker
        if: ${{ success() }}

      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::test

      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ env.IMAGE_NAME }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "test"
          tag_semver: true
          context: docker
# ================================================
